# Generated by Django 2.1.7 on 2019-03-26 23:00

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('berlin', django.db.models.manager.Manager()),
            ],
        ),
    ]
