# Generated by Django 2.1.7 on 2019-05-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190518_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='default.svg', upload_to='profile_image'),
        ),
    ]
