# Generated by Django 2.1.7 on 2019-02-26 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratelyyDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'managed': True, 'ordering': ('brand_name',), 'verbose_name_plural': 'brands'},
        ),
        migrations.AlterModelOptions(
            name='companies',
            options={'managed': True, 'ordering': ('company_name',), 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='concerns',
            options={'managed': True, 'ordering': ('concern_name',), 'verbose_name_plural': 'concerns'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': True, 'ordering': ('product_name',), 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='brands',
            name='companies',
            field=models.ManyToManyField(to='ratelyyDatabase.Companies'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='id_brand',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='companies',
            name='id_company',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='concerns',
            name='id_concern',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='brands_id_brand',
            field=models.ForeignKey(db_column='brands_id_brand', on_delete=django.db.models.deletion.CASCADE, to='ratelyyDatabase.Brands'),
        ),
        migrations.AlterField(
            model_name='products',
            name='id_product',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
