# Generated by Django 2.1.7 on 2019-03-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratelyyDatabase', '0003_auto_20190301_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concern',
            name='rating',
            field=models.CharField(blank=True, choices=[('0', 'Neutral'), ('1', 'Ethical'), ('2', 'Unethical'), ('Foo', '3')], default=0, max_length=45, null=True),
        ),
    ]
