# Generated by Django 2.1.7 on 2019-02-26 21:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ratelyyDatabase', '0003_auto_20190226_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='brand_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brands',
            name='brand_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='company_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='company_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
