# Generated by Django 2.1.7 on 2019-02-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratelyyDatabase', '0005_auto_20190227_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='companies',
            field=models.ManyToManyField(null=True, to='ratelyyDatabase.Companies', verbose_name='Company'),
        ),
    ]
