# Generated by Django 2.1.7 on 2019-02-27 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratelyyDatabase', '0006_auto_20190227_0209'),
        ('ratelyyDatabase', '0005_auto_20190227_0039'),
    ]

    operations = [
    ]
