# Generated by Django 2.1.7 on 2019-02-27 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratelyyDatabase', '0008_auto_20190227_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'managed': False, 'verbose_name_plural': 'products'},
        ),
    ]
