# Generated by Django 2.1.7 on 2019-02-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratelyyDatabase', '0006_auto_20190227_1021'),
        ('ratelyyDatabase', '0009_auto_20190227_1149'),
    ]

    operations = [
    ]
