# Generated by Django 2.1.7 on 2019-04-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratelyyDatabase', '0015_auto_20190429_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
