# Generated by Django 2.1.7 on 2019-04-29 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratelyyDatabase', '0017_remove_rating_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concern',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='concern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ratelyyDatabase.Concern'),
        ),
    ]
