# Generated by Django 2.1.7 on 2019-05-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratelyyDatabase', '0028_product_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added_by',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
