# Generated by Django 2.1.7 on 2019-05-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190518_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post',
        ),
    ]
