# Generated by Django 2.1.7 on 2019-05-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_post_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
