# Generated by Django 3.0.1 on 2020-02-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodbuyDatabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigTen',
            fields=[
                ('name', models.CharField(db_index=True, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'big_ten',
                'managed': True,
            },
        ),
    ]
