# Generated by Django 2.1.7 on 2019-04-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodbuyDatabase', '0002_auto_20190408_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default=2, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
