# Generated by Django 3.0.1 on 2020-02-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodbuyDatabase', '0002_bigten'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bigten',
            options={'managed': True, 'verbose_name_plural': 'Big Ten'},
        ),
    ]
