# Generated by Django 2.2.5 on 2020-02-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodbuyDatabase', '0003_auto_20200220_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='downvote_counter',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Scanned Counter'),
        ),
        migrations.AddField(
            model_name='product',
            name='upvote_counter',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Scanned Counter'),
        ),
    ]
