# Generated by Django 2.2.5 on 2020-02-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodbuyDatabase', '0004_auto_20200224_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='downvote_counter',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Downvote Counter'),
        ),
        migrations.AlterField(
            model_name='product',
            name='upvote_counter',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Upvote Counter'),
        ),
    ]
