# Generated by Django 2.1.7 on 2019-04-16 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goodbuyDatabase', '0009_productpriceinstore_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpriceinstore',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='product',
            name='group',
        ),
        migrations.AddField(
            model_name='productpriceinstore',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpriceinstore',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='productpriceinstore',
            table='product_price_in_store',
        ),
        migrations.DeleteModel(
            name='ProductGroup',
        ),
    ]
