# Generated by Django 2.1.7 on 2019-04-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodbuyDatabase', '0010_auto_20190416_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='rating',
            table='ratings',
        ),
        migrations.AlterModelTable(
            name='store',
            table='stores',
        ),
    ]
