# Generated by Django 2.1.7 on 2019-04-29 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodbuyDatabase', '0016_auto_20190429_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='name',
        ),
    ]
