# Generated by Django 2.1.7 on 2019-04-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodbuyDatabase', '0018_auto_20190429_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='anm_description',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='cnc_description',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='env_description',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
