# Generated by Django 2.1.7 on 2019-05-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodbuyDatabase', '0032_auto_20190513_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stat_counter',
            new_name='scanned_counter',
        ),
    ]
