# Generated by Django 2.1.7 on 2019-05-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodbuyDatabase', '0035_auto_20190514_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='certificate',
            field=models.ManyToManyField(to='goodbuyDatabase.Certificate'),
        ),
    ]
