# Generated by Django 2.1.7 on 2019-05-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodbuyDatabase', '0038_auto_20190515_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='certificate',
            field=models.ManyToManyField(blank=True, null=True, to='goodbuyDatabase.Certificate'),
        ),
    ]
