# Generated by Django 2.1.7 on 2019-05-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodbuyDatabase', '0040_auto_20190516_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='certificate',
            field=models.ManyToManyField(blank=True, to='goodbuyDatabase.Certificate'),
        ),
    ]
