# Generated by Django 2.1.7 on 2019-05-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodbuyDatabase', '0041_auto_20190518_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default.svg', null=True, upload_to='product_image'),
        ),
    ]
