# Generated by Django 2.1.7 on 2019-04-08 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratelyyDatabase', '0004_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concern',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ratelyyDatabase.Rating'),
        ),
    ]
