# Generated by Django 2.1.7 on 2019-04-15 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratelyyDatabase', '0007_auto_20190415_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceInStore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratelyyDatabase.Product')),
            ],
        ),
    ]
