# Generated by Django 2.1.7 on 2019-04-15 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratelyyDatabase', '0008_productpriceinstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpriceinstore',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ratelyyDatabase.Store'),
            preserve_default=False,
        ),
    ]
