# Generated by Django 2.1.7 on 2019-04-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratelyyDatabase', '0019_auto_20190429_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='cnc_description',
            new_name='hmn_description',
        ),
    ]
