# Generated by Django 2.1.7 on 2019-04-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratelyyDatabase', '0021_auto_20190429_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='anm_description',
            new_name='animals_description',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='env_description',
            new_name='environment_description',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='hmn_description',
            new_name='humans_description',
        ),
    ]
