# Generated by Django 2.1.7 on 2019-04-29 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratelyyDatabase', '0022_auto_20190429_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='concern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ratelyyDatabase.Concern', unique=True),
        ),
    ]
