# Generated by Django 2.1.7 on 2019-04-29 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratelyyDatabase', '0026_auto_20190429_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'managed': True, 'ordering': ('concern', 'id')},
        ),
    ]
